version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - ~/.bitgodine/dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    networks:
      - dgraph
    restart: on-failure
    command: dgraph zero --my=zero:5080

  server:
    image: dgraph/dgraph:latest
    volumes:
      - ~/.bitgodine/dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    networks:
      - dgraph
    restart: on-failure
    command: dgraph alpha --my=server:7080 --lru_mb=12288 --zero=zero:5080

  ratel:
    image: dgraph/dgraph:latest
    volumes:
      - ~/.bitgodine/dgraph:/dgraph
    ports:
      - 8000:8000
    networks:
      - dgraph
    command: dgraph-ratel

volumes:
  dgraph:

networks:
  dgraph:
