version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    container_name: zero
    volumes:
      - ~/.bitgodine/dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    networks:
      - dgraph
    restart: on-failure
    command: dgraph zero --my=zero:5080

  server:
    image: dgraph/dgraph:latest
    volumes:
      - ~/.bitgodine/dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    networks:
      - dgraph
    restart: on-failure
    command: dgraph alpha --my=server:7080 --lru_mb=12288 --zero=zero:5080

  ratel:
    image: dgraph/dgraph:latest
    container_name: ratel
    volumes:
      - ~/.bitgodine/dgraph:/dgraph
    ports:
      - 8000:8000
    networks:
      - dgraph
    command: dgraph-ratel

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      # - POSTGRES_HOST=bitgodine
      - POSTGRES_USER=bitgodine
      - POSTGRES_PASSWORD=bitgodine
      - POSTGRES_DB=bitgodine
    ports:
      - 5432:5432
    volumes:
      - ~/.bitgodine/postgresql:/var/lib/postgresql
    networks:
      - dgraph

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 9876:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=patrick.jusic@protonmail.com
      - PGADMIN_DEFAULT_PASSWORD=bitgodine
    links:
      - postgres
    logging:
      driver: none
    networks:
      - dgraph

volumes:
  dgraph:

networks:
  dgraph:
