version: "3.7"

x-git-args: &git-args
  GITHUB_TOKEN: ${GITHUB_TOKEN:-612359e5086512e1906ed81ce0c797678f52274f}

x-pg-env: &pg-env
  POSTGRES_USER: &pg-user ${POSTGRES_USER:-bitgodine}
  POSTGRES_PASSWORD: &pg-psw ${POSTGRES_PASSWORD:-bitgodine}
  POSTGRES_DB: &pg-db ${POSTGRES_DB:-bitgodine}
x-pgadmin-env: &pgadmin-env
  PGADMIN_DEFAULT_EMAIL: patrick.jusic@toggl.com
  PGADMIN_DEFAULT_PASSWORD: *pg-user

x-network: &network
  networks:
    - bitgodine

services:
  bitcoind:
    image: kylemanna/bitcoind
    container_name: bitcoind
    volumes:
      - bitcoind-data:/bitcoin/.bitcoin
    ports:
      - 8333:8333
      - 127.0.0.1:8332:8332
    <<: *network

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      <<: *pg-env
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
    <<: *network

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/redis-data/data
    restart: always
    <<: *network

  parser:
    container_name: parser
    image: xn3cr0nx/bitgodine_parser
    command: ./bitgodine --debug -r=false --db /badger --blocksDir /bitcoin --skipped 300000 --file 1000 --restored 20000000
    volumes:
      - bitcoind-data:/bitcoin
      - bolt:/bolt
      - badger:/badger
      - ./config:/root/config
    <<: *network
    restart: always

  server:
    container_name: server
    image: xn3cr0nx/bitgodine_server
    ports:
      - 3000:3000
    volumes:
      - badger:/badger
      - analysis:/analysis
      - ./config:/root/config
    <<: *network

  clusterizer:
    container_name: clusterizer
    image: xn3cr0nx/bitgodine_clusterizer
    command: ./bitgodine --debug -r=false --utxo /utxoset/utxoset.db -o /utxoset
    #command: ./bitgodine cluster export --dgHost dgraph_server -o /utxoset
    volumes:
      - utxoset:/utxoset
      - badger:/badger
      - disjoint:/disjoint
      - ./config:/root/config
    <<: *network

  spider:
    container_name: spider
    image: xn3cr0nx/bitgodine_spider
    volumes:
      - ./config:/root/config
    depends_on:
      - postgres
    <<: *network

volumes:
  dgraph:
  badger:
    driver: local
    driver_opts:
      type: ext4
      device: /mnt/sdb
      o: bind
  analysis:
  bolt:
  utxoset:
  disjoint:
  postgresql:
    # driver: local
    # driver_opts:
    #   type: ext4
    #   device: /mnt/sdc1
    #   o: bind
  redis:
    driver: local
    driver_opts:
      type: ext4
      device: /mnt/sdb
      o: bind
  bitcoind-data:
    # driver: local
    # driver_opts:
    #   type: ext4
    #   device: /mnt/sdb1
    #   o: bind

networks:
  bitgodine:
    name: bitgodine
