{
  set { 
   _:coinbase <hash> "0000000000000000000000000000000000000000000000000000000000000000" .

   _:block <hash> "00000000dc55860c8a29c58d45209318fa9e9dc2c1833a7226d86bc465afc6e5" . 
   _:block <previous> "00000000b5ef0ea215becad97402ce59d1416fe554261405cda943afd2a8c8f2" . 
   _:block <height> "181" . 
   _:block <time> "1/12/2009, 7:02:13 AM GMT+1" . 
   _:block <transaction> _:transaction1 . 
   _:block <transaction> _:transaction2 . 

   _:transaction1 <hash> "8347cee4a1cb5ad1bb0d92e86e6612dbf6cfc7649c9964f210d4069b426e720a" .
   _:transaction1 <locktime> "0" .
   _:transaction1 <input> _:input10 .
   _:transaction1 <output> _:output10 .
     
   _:input10 <hash> _:coinbase . 
   _:input10 <vout> "" . 

   _:output10 <value> "50" .
   _:output10 <address> "testAddress" .

   _:transaction2 <hash> "a16f3ce4dd5deb92d98ef5cf8afeaf0775ebca408f708b2146c4fb42b41e14be" .
   _:transaction2 <locktime> "0" .
   _:transaction2 <input> _:input20 .
   _:transaction2 <output> _:output20 .
   _:transaction2 <output> _:output21 .
     
   _:input20 <hash> "f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16" . 
   _:input20 <vout> "1" . 

   _:output20 <value> "10" .
   _:output20 <address> "testAddress" .
   _:output21 <value> "30" .
   _:output21 <address> "testAddress" .
  }

  set {
    _:clusters <size> "0"^^<xs:int> .
  
  	_:clusters <parents> _:p1 .
  	_:clusters <parents> _:p2 .
  	_:p1 <pos> "0"^^<xs:int> .
  	_:p1 <parent> "0"^^<xs:int> .
  	_:p2 <pos> "1"^^<xs:int> .
  	_:p2 <parent> "3"^^<xs:int> .
  
  	_:clusters <ranks> _:r1 .
  	_:clusters <ranks> _:r2 .
  	_:r1 <pos> "0"^^<xs:int> .
  	_:r1 <rank> "1"^^<xs:int> .
  	_:r2 <pos> "1"^^<xs:int> .
  	_:r2 <rank> "2"^^<xs:int> .
  
  	_:clusters <set> _:c1 .
  	_:clusters <set> _:c2 .
  
  	_:c1 <addresses> _:a11 .
  	_:c1 <addresses> _:a12 .
  	_:c1 <cluster> "5"^^<xs:int> .
  	_:a11 <address> "1BoatSLRHtKNngkdXEeobR76b53LETtpyT"^^<xs:string> .
 		_:a12 <address> "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2"^^<xs:string> .
  
  	_:c2 <addresses> _:a21 .
  	_:c2 <addresses> _:a22 .
  	_:c2 <cluster> "6"^^<xs:int> .
  	_:a21 <address> "3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy"^^<xs:string> .
 		_:a22 <address> "bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq"^^<xs:string> .
 }
}