{
	q(func: has(inputs)) @cascade {
		uid
    block
    hash
    inputs @filter(eq(hash, "a16f3ce4dd5deb92d98ef5cf8afeaf0775ebca408f708b2146c4fb42b41e14be") AND eq(vout, 1)){
      hash
      vout
    }
	}
}